---
- name: Install logstash with kibana
  apt:
      name: logstash
      update_cache: yes


#starting kibana

- name: starting logstash
  service:
          name: logstash
          state: started
          enabled: yes
