---
- name: Elksetup using ansible
  hosts: ELKnode
  remote_user: itachi
  become: yes
  become_user: itachi

  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: logstash }
  - { role: kibana } 
  - { role: filebeat }
  - { role: restartservice }
