---


# Installing kibana with apt
- name: Installing kibana with apt
  apt:
      name: kibana
      state: present
      update_cache: yes


#updating config file in kibana

- name: updating config file to allow outside access
  lineinfile:
            destfile: /etc/kibana/kibana.yml
            regexp: 'server.host:'
            line: 'server.host: 0.0.0.0'


- name: Defining server port
  lineinfile:
            destfile: /etc/kibana/kibana.yml
            regexp: 'server.port:'
            line: 'server.port: 5601'

- name: Defining Elasticsearch URL
  lineinfile:
            destfile: /etc/kibana/kibana.yml
            regexp: 'elasticsearch.hosts:'
            line: 'elasticsearch.hosts: "http://localhost:9200"'



# Starting kibana
- name: Starting kibana
  service:
          name: kibana
          state: started
          enabled: yes